<FLOAD "NCOMPDEC.MSUBR">

<FLOAD "PEEP.MSUBR">

<GROUP-LOAD "NCDRIVE.MUD">

<MAPF <> <FUNCTION (X) <FLOAD <STRING .X ".MSUBR">>>
      ("NSYMANA" "NDEATH" "NCODGEN" "NSTRGEN" "NCARGEN" "NLNQGEN" "NMMQGEN"
       "NNEWREP" "NMAPGEN" "NNOTGEN")>

