<DEFINITIONS "DEBUGRDEFS">

<USE "NEWSTRUC">

<MSETG PRED-CHAR !\>
<MSETG NEXXT-CHAR !\>
<MSETG FAST-CHAR !\>
<MSETG WEER-CHAR !\>
<MSETG BODY-CHAR !\>
<MSETG FLUSH-CHAR !\>
<MSETG CHAR-LIST
       <STRING ,PRED-CHAR ,NEXXT-CHAR ,FAST-CHAR
	       ,WEER-CHAR ,BODY-CHAR ,FLUSH-CHAR <ASCII 27>>>

<MSETG OPHF 0>
<MSETG NEXXT 1>
<MSETG BODY 2>
<MSETG FAST 3>
<MSETG WEER 4>
<MSETG PRED 5>
<MSETG FLUSH-STATE 6>

<GDECL (DEBSTATE DEB-LEVEL REPEAT-COUNT MACRO-LEVEL
	INDENT-INC INDENT-DIF INDENT-DIF) FIX
       (DEB-IN DEB-OUT LO PREDICATE) ANY
       (EVAL-IN EVAL-OUT) ATOM
       (SAVED-DEB-LEVEL) FIX
       (SAVED-EXPR) ANY
       (LAST-CHAR) CHARACTER
       (MACRO-FLAG INFULL? FORM-FAST SELF-FAST OUT-FAST OUT-UNIQUE)
       <OR !<FALSE!> ATOM>>

<END-DEFINITIONS>
